timezone: America/Los_Angeles
encoding: utf-8

url: https://asn-plus.cssnr.com

author: Shane
site_name: ASN Plus

menu:
    - name: Home
      link: /
    - name: Documentation
      link: /docs/
    - name: Screen Shots
      link: /screenshots/

github_name: cssnr/asn-plus
github_url: https://github.com/cssnr/asn-plus

chrome_id: phcbcnpmcbkcnijkpfohkdmcofcofibh
chrome_url: https://chromewebstore.google.com/detail/asn-plus/phcbcnpmcbkcnijkpfohkdmcofcofibh

firefox_id: asn-plus
firefox_url: https://addons.mozilla.org/addon/asn-plus

discord_server: 899171661457293343
discord_invite: https://discord.gg/wXy6m2X8wY

feedback_link: https://cssnr.github.io/feedback/?app=ASN%20Plus
relay_url: https://relay.cssnr.com/discord/1258944618389569566
